Repository gardener/cc-utils, pull requests merged in 2019-10, with the labels that each got.

#352 disable github api access logging
  ccc/github.py
Labels: needs/ok-to-test

#353 access gh technical user by name
  model/github.py
Labels: needs/ok-to-test

#351 Also report file path for found malware
  concourse/steps/scan_container_images.mako
  concourse/steps/scan_container_images.py
Labels: needs/ok-to-test

#354 remove technicalUser code
  model/github.py
  test/model/github_test.py
Labels: needs/ok-to-test

#356 Create ci package
  ci/__init__.py
  ci/util.py
  test/ci/util_test.py
  util.py
Labels: needs/ok-to-test

#361 Add caching support to http_adapter
  http_requests.py
Labels: needs/ok-to-test

#358 switch mapping-order in steps
  concourse/model/step.py
  concourse/model/traits/component_descriptor.py
  concourse/model/traits/image_scan.py
  concourse/model/traits/image_upload.py
  concourse/model/traits/meta.py
  concourse/model/traits/publish.py
  concourse/model/traits/update_component_deps.py
  concourse/model/traits/version.py
  concourse/templates/default.mako
Labels: needs/ok-to-test

#359 move versionfile to ci package
  .ci/pipeline_definitions
  Dockerfile
  VERSION
  ci/version
  cli/setup.py
  setup.py
Labels: needs/ok-to-test, reviewed/do-not-merge

#363 Add util function to print gardener-cicd-libs version
  ci/util.py
Labels: needs/ok-to-test

#366 Add alicloud model
  model/alicloud.py
Labels: needs/ok-to-test

#367 change attribute naming for alicloud to use underscore case
  model/alicloud.py
Labels: needs/ok-to-test, reviewed/ok-to-test

#368 full qualified image name as upload name for protocode
  product/model.py
  product/scanning.py
Labels: needs/ok-to-test

#369 make yaml linter configurable
  ci/util.py
Labels: needs/ok-to-test
