Repository gardener/cc-utils, pull requests merged in 2020-08, with the labels that each got.

#457 pin resource in context manager
  concourse/client/util.py
Labels: needs/ok-to-test

#459 remove CC monitoring
  cli/gardener_ci/landscape.py
  landscape_setup/monitoring.py
  model/concourse.py
  model/monitoring.py
  test/model/monitoring_test.py
Labels: needs/ok-to-test

#464 omit run attr for prepare-step
  concourse/steps/publish.mako
  concourse/templates/default.mako
Labels: needs/ok-to-test

#462 Publish images in parallel
  concourse/steps/publish.mako
Labels: needs/ok-to-test, reviewed/ok-to-test

#466 Adjust to changes in google apis
  ccc/grafeas.py
  protecode/scanning_util.py
Labels: reviewed/ok-to-test

#467 Clean-up and future-proof grafeas imports
  ccc/grafeas.py
  protecode/scanning_util.py
Labels: needs/ok-to-test

#468 Add backwards-compatibility-coding for ContainerAnalysisClient
  ccc/grafeas.py
Labels: needs/ok-to-test

#470 Require component-descriptor trait for release-trait
  concourse/model/traits/release.py
  concourse/steps/release.mako
  concourse/steps/release.py
Labels: needs/ok-to-test

#461 add schema-version to component-descriptor
  product/model.py
  test/concourse/steps/update_component_deps_test.py
Labels: needs/ok-to-test, reviewed/do-not-merge

#471 Make code compatible to new google libs versions
  ccc/grafeas.py
  requirements.txt
Labels: needs/ok-to-test
