Repository gardener/cc-utils, pull requests merged in 2020-12, with the labels that each got.

#501 Adapt release note extraction to use new categories
  github/release_notes/util.py
  test/github/release_notes/util_test.py
Labels: needs/ok-to-test, needs/review, size/m

#498 Add initial support for labels to protecode scanning
  protecode/util.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/xs

#500 Handle circular dependencies when depending on publish
  concourse/model/job.py
Labels: needs/ok-to-test, needs/review, size/s

#506 use custom oci-client for verbatim image-replication
  concourse/templates/default.mako
  container/registry.py
  model/container_registry.py
  oci/__init__.py
  oci/auth.py
  oci/client.py
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/m

#507 Add support for defining labels in the component-descriptor trait
  concourse/model/traits/component_descriptor.py
  concourse/steps/component_descriptor.mako
  concourse/steps/component_descriptor.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/s

#505 Add support for defining labels in the publish-trait
  concourse/model/traits/publish.py
  concourse/steps/component_descriptor.mako
Labels: needs/changes, needs/ok-to-test, needs/review, size/xs

#509 inputs from steps for component-descriptor-trait
  concourse/model/traits/component_descriptor.py
Labels: needs/ok-to-test, needs/review, size/s

#504 Prepare codepath for CTF use
  concourse/steps/component_descriptor.mako
Labels: needs/ok-to-test, needs/review, size/s

#513 Add Component Spec to dependencies
  .ci/component_descriptor
  .ci/pipeline_definitions
  .ci/set_dependency_version
  requirements.txt
Labels: needs/changes, needs/ok-to-test, needs/review, size/m
