Repository gardener/cc-utils, pull requests merged in 2020-11, with the labels that each got.

#491 Add support for custom release-tags
  concourse/model/traits/release.py
  concourse/steps/release.mako
  concourse/steps/release.py
  test/concourse/steps/release_test.py
Labels: needs/ok-to-test, needs/review, size/m

#492 Add cli function to send emails
  cli/gardener_ci/notify.py
Labels: needs/changes, needs/ok-to-test, size/s

#493 only emit component-versions once
  ci/version
Labels: needs/ok-to-test, size/xs

#496 Improve handling of triages
  protecode/scanning_util.py
Labels: needs/ok-to-test, needs/review, size/s

#497 Add Release Note Categories
  doc/release_notes.rst
  github/release_notes/renderer.py
  test/github/release_notes/renderer_test.py
Labels: needs/ok-to-test, size/m
