Repository gardener/cc-utils, pull requests merged in 2021-04, with the labels that each got.

#589 Added: special handling for missing media type in put_manifest
  oci/client.py
Labels: needs/ok-to-test, needs/review, size/xs

#585 add decryption to secrets server client
  ccc/secrets_server.py
  ctx.py
Labels: needs/changes, needs/ok-to-test, needs/review, reviewed/do-not-merge, size/m

#590 Fixed: dict as access type now handled
  product/v2.py
Labels: needs/review, reviewed/ok-to-test, size/xs
