Repository gardener/cc-utils, pull requests merged in 2021-07, with the labels that each got.

#631 Init compliance db
  ccc/compliancedb.py
  dso/compliancedb/__init__.py
  dso/compliancedb/db.py
  dso/compliancedb/model.py
Labels: needs/ok-to-test, needs/review, size/s

#632 enable plaintext as encryption mode
  ccc/secrets_server.py
  model/secret.py
Labels: needs/ok-to-test, needs/review, reviewed/do-not-merge, size/s

#628 Fixes invalid oci artifact if old component-descriptor media typ and nexus content-length bug
  oci/__init__.py
  oci/client.py
Labels: needs/ok-to-test, needs/review, size/xs

#633 Workaround ghcr registry and media type distribution
  oci/client.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/s

#635 Fixed: debug flag in code
  oci/__init__.py
Labels: needs/ok-to-test, needs/review, size/xs

#637 return response objects from oci methods
  container/util.py
  oci/__init__.py
Labels: needs/ok-to-test, needs/review, size/xs
