Repository gardener/cc-utils, pull requests merged in 2021-06, with the labels that each got.

#608 Add scan sources filter
  cli/gardener_ci/whitesource_cli.py
  concourse/model/traits/scan_sources.py
  concourse/steps/scan_sources.mako
  concourse/steps/scan_sources.py
  whitesource/client.py
  whitesource/component.py
  whitesource/filters.py
  whitesource/model.py
  whitesource/util.py
Labels: needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#614 yaml2json: Convert non-serializable objects to string
  cli/gardener_ci/yaml2json.py
Labels: needs/ok-to-test, needs/review, size/xs

#613 move uploading of component descriptor to its own step
  concourse/model/traits/component_descriptor.py
  concourse/steps/component_descriptor.mako
  concourse/steps/release.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/s

#621 Update GH PR template
  .github/pull_request_template.md
Labels: needs/ok-to-test, needs/review, size/xs

#623 pass ctx_repo-objects, instead of just base-urls
  cnudie/retrieve.py
  concourse/model/traits/component_descriptor.py
  concourse/steps/component_descriptor.py
  concourse/steps/notification.mako
  product/v2.py
Labels: needs/ok-to-test, needs/review, size/m

#627 fix null pointer
  cnudie/replicate.py
Labels: needs/ok-to-test, needs/review, size/xs

#620 Improve cfg-factory convenience a little bit
  model/__init__.py
Labels: needs/ok-to-test, needs/review, size/xs
