Repository gardener/cc-utils, pull requests merged in 2021-11, with the labels that each got.

#659 handle unresolvable component-references as an error
  concourse/steps/release.py
Labels: needs/review, size/xs, needs/ok-to-test

#661 switch default oci-image-builder to docker
  concourse/model/traits/publish.py
Labels: needs/review, needs/ok-to-test

#662 Add additional Azure Python modules for Garden Linux tests
  requirements.gardenlinux.txt
Labels: needs/review, size/xs, needs/ok-to-test

#663 make target team for secret repl configurable
  model/concourse.py
Labels: needs/review, size/xs, needs/ok-to-test

#665 adapt siging cfg model to new service auth
  model/delivery.py
Labels: needs/review, size/xs, needs/ok-to-test, needs/changes

#668 paginate through apps-list
  protecode/client.py
Labels: needs/review, size/xs, needs/ok-to-test
