Repository gardener/cc-utils, pull requests merged in 2021-05, with the labels that each got.

#592 removes special handling of dicts in resource access
  product/v2.py
Labels: needs/ok-to-test, needs/review, size/xs

#595 change the add_dependency_command oci image default from local to external
  cli/gardener_ci/productutil_v2.py
Labels: needs/ok-to-test, needs/review, size/xs

#596 add encrypted secret name to env
  concourse/templates/default.mako
  model/secrets_server.py
Labels: needs/ok-to-test, needs/review, size/xs

#598 add secret key, alg to notification env
  concourse/templates/default.mako
Labels: needs/ok-to-test, needs/review, size/xs

#599 use detailed component descriptor filename as github asset name
  concourse/steps/release.py
Labels: needs/ok-to-test, needs/review, size/xs

#600 make cfg_factory serialiseable
  model/__init__.py
Labels: needs/ok-to-test, needs/review, size/xs

#603 add encrypt data to secrets server
  ccc/secrets_server.py
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/s

#602 extend job mapping model
  model/concourse.py
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs

#605 Add oci-image support for WhiteSource
  oci/__init__.py
  whitesource/client.py
  whitesource/component.py
  whitesource/util.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/m

#606 Add CTF support for ScanSources
  cli/gardener_ci/whitesource_cli.py
  concourse/steps/component_descriptor_util.py
  concourse/steps/scan_sources.mako
  concourse/steps/scan_sources.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/m

#607 extend model for uam redesign
  model/concourse.py
Labels: needs/ok-to-test, needs/review, size/s
