Repository gardener/cc-utils, pull requests merged in 2021-02, with the labels that each got.

#563 Configure root logger in cli.py
  checkmarx/project.py
  ci/log.py
  cli/gardener_ci/cli_gen.py
  cli/gardener_ci/whdutil.py
  protecode/scanning_util.py
  protecode/util.py
  whitesource/client.py
  whitesource/component.py
  whitesource/util.py
Labels: needs/ok-to-test, needs/review, size/s

#564 Update WHD logging usage and introduce `force` flag
  ci/log.py
  cli/gardener_ci/cli_gen.py
  cli/gardener_ci/whdutil.py
  ctx.py
  whd/__init__.py
  whd/server.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/s

#565 Build kaniko-image from scratch using pypi
  Dockerfile.kaniko
Labels: needs/ok-to-test, needs/review, size/xs

#568 Update WHD webserver, adjust logging
  cli/gardener_ci/whdutil.py
  requirements.whd.txt
  whd/__init__.py
Labels: needs/ok-to-test, needs/review, size/s

#569 replace FluentIterabel in cnudie.util
  cnudie/util.py
Labels: needs/ok-to-test, needs/review, size/xs

#566 Support oAuth in Protecode Client
  ccc/protecode.py
  model/base.py
  model/protecode.py
  protecode/client.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/m

#572 restore method write_component_descriptor_to_dir
  product/v2.py
Labels: needs/review, reviewed/ok-to-test, size/s
