Repository gardener/cc-utils, pull requests merged in 2021-01, with the labels that each got.

#521 Cd add git main repo
  concourse/steps/component_descriptor.mako
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/s

#536 Add support for depending on traits
  concourse/model/job.py
  concourse/model/step.py
  concourse/model/traits/component_descriptor.py
  concourse/model/traits/draft_release.py
  concourse/model/traits/image_alter.py
  concourse/model/traits/image_scan.py
  concourse/model/traits/meta.py
  concourse/model/traits/publish.py
  concourse/model/traits/pullrequest.py
  concourse/model/traits/release.py
  concourse/model/traits/scan_sources.py
  concourse/model/traits/update_component_deps.py
  concourse/model/traits/version.py
Labels: needs/ok-to-test, needs/review, size/s

#545 Adjust whitesource client to websockets
  cli/gardener_ci/whitesource_cli.py
  concourse/steps/scan_sources.py
  requirements.txt
  whitesource/client.py
  whitesource/component.py
  whitesource/model.py
  whitesource/util.py
Labels: needs/changes, needs/ok-to-test, needs/review, size/m

#546 get cd main repo by label
  cnudie/util.py
  concourse/steps/update_component_deps.py
  test/cnudie/cnudie_util_test.py
Labels: needs/ok-to-test, needs/review, size/m

#547 optionally accept components-resolv-function
  cnudie/util.py
Labels: needs/ok-to-test, needs/review, size/xs

#551 Fix kaniko build some more
  concourse/steps/build_oci_image.mako
Labels: needs/ok-to-test, needs/review, size/xs

#549 Multithread whitesource client
  cli/gardener_ci/whitesource_cli.py
  concourse/model/traits/scan_sources.py
  concourse/steps/scan_sources.mako
  concourse/steps/scan_sources.py
  model/whitesource.py
  whitesource/client.py
  whitesource/component.py
  whitesource/util.py
Labels: needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/l
