Repository gardener/cc-utils, pull requests merged in 2021-03, with the labels that each got.

#574 Add swift client in the requirements
  requirements.txt
Labels: needs/ok-to-test, needs/review, size/xs

#573 add support for ctf in draft release notes
  cnudie/util.py
  concourse/steps/draft_release.mako
  concourse/steps/release.mako
  concourse/steps/release.py
  test/cnudie/cnudie_util_test.py
  test/concourse/steps/release_test.py
Labels: needs/changes, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#579 refactor concourse-api-client
  concourse/client/api.py
Labels: needs/ok-to-test, needs/review, size/s

#580 Replace common stack-traces in WHD with proper log messages
  whd/dispatcher.py
Labels: needs/ok-to-test, needs/review, size/s

#581 Ignore dev component versions for update pull-request
  concourse/model/traits/update_component_deps.py
  concourse/steps/update_component_deps.mako
  concourse/steps/update_component_deps.py
  product/v2.py
  test/concourse/steps/update_component_deps_test.py
  test/version_test.py
  version.py
Labels: needs/ok-to-test, needs/review, size/s

#510 add base component archive to simplify the usage of the component-cli
  concourse/steps/component_descriptor.mako
Labels: needs/changes, needs/ok-to-test, needs/review, size/xs
