Repository gardener/cc-utils, pull requests merged in 2022-07, with the labels that each got.

#732 add annotations field to OciBlobRef
  oci/model.py
  test/oci/oci_model_test.py
Labels: needs/review, needs/ok-to-test, size/s

#736 oci ref annotations
  cli/gardener_ci/_oci.py
  container/util.py
  oci/__init__.py
  oci/model.py
  oci/workarounds.py
  product/v2.py
  test/oci/oci_model_test.py
Labels: needs/review, needs/ok-to-test, reviewed/do-not-merge, size/m, merge/squash

#739 Revert blob model changes
  product/v2.py
Labels: reviewed/ok-to-test, needs/review, size/xs

#740 Fallback PR action to unknown
  whd/model.py
Labels: needs/review, size/xs, needs/ok-to-test

#741 Don't call version trait write_callback if it is None.
  concourse/steps/version.mako
Labels: needs/review, size/xs, needs/ok-to-test

#742 Write filesystem paths to deliverydb
  dso/model.py
  protecode/util.py
Labels: needs/review, needs/ok-to-test, size/s
