Repository gardener/cc-utils, pull requests merged in 2022-03, with the labels that each got.

#693 implement multiarch build and publishing
  concourse/model/traits/publish.py
  concourse/steps/build_oci_image.mako
  concourse/steps/build_oci_image.py
  concourse/steps/publish.mako
  concourse/templates/default.mako
Labels: needs/review, needs/ok-to-test, size/m

#696 exclude archived repositories from pipeline replication
  cli/gardener_ci/_concourse.py
  concourse/enumerator.py
  concourse/replicator.py
Labels: needs/ok-to-test, reviewed/lgtm

#679 refactor protecode upload coding
  protecode/model.py
  protecode/scanning_util.py
  protecode/util.py
Labels: reviewed/ok-to-test, needs/review, needs/ok-to-test, size/m, needs/changes

#697 Determine concourse main team from explicit config
  ccc/concourse.py
  model/concourse.py
Labels: needs/review, needs/ok-to-test, size/s
