Repository gardener/cc-utils, pull requests merged in 2022-06, with the labels that each got.

#675 Refine notification handling
  concourse/factory.py
  concourse/model/step.py
  concourse/model/traits/component_descriptor.py
  concourse/model/traits/draft_release.py
  concourse/model/traits/image_scan.py
  concourse/model/traits/meta.py
  concourse/model/traits/publish.py
  concourse/model/traits/pullrequest.py
  concourse/model/traits/release.py
  concourse/model/traits/scan_sources.py
  concourse/model/traits/update_component_deps.py
  concourse/model/traits/version.py
  concourse/templates/default.mako
  test/concourse/model/job_test.py
  test/concourse/model/step_test.py
  test/concourse/steps/notification_test.py
  test/concourse/steps/test_utils.py
Labels: needs/review, needs/rebase, needs/ok-to-test, size/m

#724 Use replace-binary to update scans
  cli/gardener_ci/protecode_cli.py
  protecode/client.py
  protecode/scanning_util.py
Labels: needs/review, needs/ok-to-test, size/m

#722 Write detected libraries to deliverydb
  ci/util.py
  clamav/cnudie.py
  concourse/steps/malware_scan.mako
  concourse/steps/os_id.py
  delivery/client.py
  dso/model.py
  protecode/util.py
Labels: reviewed/ok-to-test, needs/review, needs/rebase, needs/ok-to-test, needs/second-opinion, size/l, needs/changes

#729 Lazy load component-cli and helm
  Dockerfile
  bin/component-cli
  bin/helm
Labels: needs/review, needs/ok-to-test, size/s, needs/changes
