Repository gardener/cc-utils, pull requests merged in 2022-10, with the labels that each got.

#758 Remove legacy component descriptor retrieval
  cnudie/retrieve.py
Labels: needs/review, needs/ok-to-test, reviewed/do-not-merge, size/m

#760 fix error when removing from list in loop
  container/util.py
Labels: needs/review, needs/ok-to-test, size/s

#763 UnboundLocalError: local variable 'issue' referenced before assignment
  github/compliance/report.py
Labels: needs/review, size/xs, needs/ok-to-test

#764 Add support for AwsProfile autorotation
  cfg_mgmt/aws.py
  cfg_mgmt/rotate.py
Labels: needs/review, needs/ok-to-test, reviewed/do-not-merge, size/m

#766 Update docker.py
  cli/gardener_ci/docker.py
Labels: reviewed/ok-to-test, needs/review, size/xs

#767 install openstack sdk
  requirements.txt
Labels: needs/review, size/xs, needs/ok-to-test

#768 update base job image to 0.82.0
  Dockerfile
Labels: needs/review, size/xs, needs/ok-to-test
