Repository gardener/cc-utils, pull requests merged in 2022-08, with the labels that each got.

#747 `write_callback` needs to be defined for #741 to work properly.
  concourse/steps/version.mako
Labels: needs/review, size/xs, needs/ok-to-test, needs/changes

#746 Factor out `find_branch_info`
  concourse/steps/os_id.py
  delivery/util.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes

#750 Cosign repository
  model/signing_server.py
Labels: needs/review, size/xs, needs/ok-to-test
