Repository gardener/cc-utils, pull requests merged in 2022-04, with the labels that each got.

#703 Refactor: Eliminate prints in product.v2
  product/v2.py
Labels: needs/review, size/xs, needs/ok-to-test

#706 Add model and rotation for BTP application certificates
  cfg_mgmt/btp_application_certificate.py
  cfg_mgmt/btp_service_binding.py
  cfg_mgmt/rotate.py
  model/btp_application_certificate.py
Labels: needs/review, needs/ok-to-test, needs/second-opinion, size/l

#708 Add model and rotation for BTP application certificates
  cfg_mgmt/btp_application_certificate.py
  cfg_mgmt/btp_service_binding.py
  cfg_mgmt/rotate.py
  model/btp_application_certificate.py
  requirements.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/l

#709 Add support for on_abort-hook
  concourse/model/step.py
  concourse/templates/default.mako
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#713 Make Merge-Method Configurable
  concourse/model/traits/update_component_deps.py
  concourse/steps/update_component_deps.mako
  concourse/steps/update_component_deps.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes
