Repository gardener/cc-utils, pull requests merged in 2022-11, with the labels that each got.

#769 Change type of sprint dates from `date` to `datetime`
  delivery/model.py
  github/compliance/milestone.py
Labels: needs/review, size/xs, needs/ok-to-test

#771 Codeowner model introduction
  github/codeowners.py
Labels: needs/review, needs/ok-to-test, size/m

#772 Fix unintended parsing of `date` to `datetime`
  delivery/model.py
Labels: needs/review, size/xs, needs/ok-to-test

#770 Add func to resolve codeowner entries to gh usernames
  github/codeowners.py
Labels: needs/review, needs/rebase, needs/ok-to-test, size/s, needs/changes

#774 Pass labels rather than OCM component / artifact
  github/compliance/issue.py
  github/compliance/report.py
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#777 Change issue label prefix for ocm artefacts
  github/compliance/issue.py
Labels: needs/review, size/xs, needs/ok-to-test

#778 Add optional ctx label(s)
  github/compliance/issue.py
  github/compliance/report.py
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#779 Add optional compliance reporting url
  model/concourse.py
Labels: needs/review, size/xs, needs/ok-to-test, needs/changes

#780 Add optional explicit configuration of cfg storage
  cfg_mgmt/util.py
Labels: needs/review, size/xs, needs/ok-to-test

#782 Also accept issue template to be passed directly
  github/compliance/report.py
Labels: needs/review, size/xs, needs/ok-to-test
