Repository gardener/cc-utils, pull requests merged in 2023-09, with the labels that each got.

#888 Update sprint model
  delivery/model.py
  github/compliance/milestone.py
  github/compliance/report.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes

#890 Preparations for ocm repo mappings in Delivery-Service
  cnudie/retrieve.py
Labels: needs/review, needs/ok-to-test, size/s

#894 Comment problems found during issue update
  github/compliance/issue.py
Labels: reviewed/ok-to-test, needs/ok-to-test, size/s, needs/changes

#896 Avoid unnecessary dependencies in pipeline-graph
  concourse/model/job.py
  concourse/model/traits/publish.py
Labels: needs/review, size/xs, needs/ok-to-test
