Repository gardener/cc-utils, pull requests merged in 2023-04, with the labels that each got.

#838 Add support for OciImageIndex
  oci/__init__.py
  oci/client.py
  oci/model.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes

#832 re-implement component-cli's imagevector-add cmd
  bin/component-cli
  cli/gardener_ci/pipeline.py
  doc/traits/component_descriptor.rst
Labels: needs/review, needs/ok-to-test, size/m

#850 Do not rescore further than `LOW`
  dso/cvss.py
Labels: needs/review, size/xs, needs/ok-to-test
