Repository gardener/cc-utils, pull requests merged in 2023-08, with the labels that each got.

#874 Optionally merge release-commit from tag to default-branch
  concourse/model/traits/release.py
  concourse/steps/release.py
Labels: needs/review, needs/ok-to-test, size/s

#879 Allow passing of `ctx_repo` to override lookup `ctx_repo` in `cnudie.iter`
  cnudie/iter.py
Labels: needs/review, size/xs, needs/ok-to-test

#880 added `ignore_prerelease_versions` to `greatest_component_versions` in `cnudie.retrieve`
  cnudie/retrieve.py
Labels: reviewed/ok-to-test, needs/review, size/xs

#881 added `oci_client` to `create_default_component_descriptor_lookup` in `cnudie.retrieve`
  cnudie/retrieve.py
Labels: needs/review, size/xs

#884 Allow rescoring to `NONE` again
  dso/cvss.py
Labels: needs/review, size/xs, needs/ok-to-test
