Repository gardener/cc-utils, pull requests merged in 2024-05, with the labels that each got.

#968 Add gzip compression to delivery client metadata routes
  delivery/client.py
  http_requests.py
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#974 Enable individual malware finding tracking
  dso/model.py
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#976 Add `referenced_type` param and merge query metadata routes
  delivery/client.py
Labels: needs/review, needs/ok-to-test, size/s

#977 fix: do not reset changes from release-commit-callback
  concourse/steps/release.py
Labels: needs/review, size/xs, needs/ok-to-test
