Repository gardener/cc-utils, pull requests merged in 2024-07, with the labels that each got.

#988 fix: determine supported types by access, instead of artefact-type
  ctt/filters.py
  ctt/process_dependencies.py
  ctt/uploaders.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#987 Add support for build metadata in version string
  ccc/oci.py
  cnudie/util.py
  oci/client.py
Labels: needs/review, needs/rebase, needs/ok-to-test, size/s

#991 store helmchart-imagemap w/ same name as helmchart
  concourse/steps/release.mako
Labels: needs/review, size/xs, needs/ok-to-test

#993 Add optional `references` to `ComponentArtefactId`
  dso/model.py
Labels: needs/review, size/xs, needs/ok-to-test

#994 Add diki compliance label
  github/compliance/issue.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#992 Don't store component version for BDBA scan results
  protecode/model.py
  protecode/scanning.py
  protecode/util.py
Labels: reviewed/ok-to-test, needs/review, size/xs, needs/ok-to-test, needs/changes

#997 Add support for merged diki report
  dso/model.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1001 allow adding plain files as release-assets
  concourse/model/traits/release.py
  concourse/steps/release.mako
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#998 Do not risk inconsistencies during component updates
  concourse/steps/update_component_deps.mako
  concourse/steps/update_component_deps.py
Labels: needs/review, needs/ok-to-test, size/s
