Repository gardener/cc-utils, pull requests merged in 2024-09, with the labels that each got.

#1031 refactor: Deconstruct bdba grouping
  cli/gardener_ci/bdba.py
  protecode/scanning.py
Labels: size/xl, needs/ok-to-test, needs/second-opinion

#1036 replace daily alpine-image-build w/ github-action
  .ci/pipeline_definitions
  .github/workflows/alpine-sap.yaml
  .github/workflows/pythonapp.yml
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1037 explicitly configure platforms
  .github/workflows/alpine-sap.yaml
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#1038 Dataclasses support
  doc/lib/attributes.py
Labels: needs/review, size/s

#1041 Raise for failed BDBA scans
  protecode/client.py
  protecode/model.py
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#1033 refactor: Use resource-node for bdba custom metadata
  protecode/scanning.py
  protecode/util.py
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1046 Overhaul CTT processing behaviour
  ctt/process_dependencies.py
  gci/componentmodel.py
Labels: needs/review, needs/ok-to-test, needs/second-opinion, size/l

#1047 Fix unpatched root component descriptor on CTT retry
  ctt/process_dependencies.py
Labels: needs/review, size/xs, needs/ok-to-test

#1052 Omit `features` field from oci-platform if no contents
  concourse/steps/publish.mako
  oci/model.py
Labels: size/xs, needs/ok-to-test, reviewed/lgtm

#1050 Extend greatest_component_versions to support filtering by date range
  delivery/client.py
Labels: reviewed/ok-to-test, size/xs, reviewed/lgtm
