Repository gardener/cc-utils, pull requests merged in 2024-10, with the labels that each got.

#1054 Support multiline string in `pullrequest_body_suffix`
  concourse/steps/update_component_deps.mako
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1055 Add `signature_name` to signing server model class
  model/signing_server.py
Labels: needs/review, size/xs, needs/ok-to-test

#1057 Add helper function to parse signing algorithm according to rfc
  model/signing_server.py
Labels: needs/review, size/xs, needs/ok-to-test

#1059 fix: store a list of image-mappings
  concourse/steps/helmcharts.mako
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1060 fix: clean build-dir between package-builds
  .ci/build_python_packages
  .github/workflows/build-and-test.yaml
Labels: needs/review, size/xs, needs/ok-to-test

#1064 Remove stale properties from `signing_server` cfg model
  model/signing_server.py
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#1065 Add `artefact_extra_id` to release assets (+ actually use `purposes` and `comment` for file assets)
  concourse/model/traits/release.py
  concourse/steps/release.mako
Labels: needs/review, needs/ok-to-test, size/s

#1063 Add component-diff to release notes
  cnudie/util.py
  concourse/steps/update_component_deps.mako
  concourse/steps/update_component_deps.py
  test/cnudie/cnudie_util_test.py
Labels: needs/review, needs/ok-to-test, size/m, needs/changes

#1066 Only add private-key to git-resource if present
  concourse/resources/github.mako
Labels: needs/review, size/xs, needs/ok-to-test
