Repository gardener/cc-utils, pull requests merged in 2024-08, with the labels that each got.

#1004 fix: guard against adding step-output multiple times
  concourse/model/step.py
Labels: needs/review, size/xs, needs/ok-to-test

#995 Rm clamav related coding
  ccc/clamav.py
  clamav/__init__.py
  clamav/client.py
  clamav/cnudie.py
  clamav/model.py
  clamav/report.py
  clamav/routes.py
  clamav/scan.py
  clamav/util.py
  cli/gardener_ci/_clamav.py
  concourse/model/traits/filter.py
  concourse/model/traits/image_scan.py
  concourse/steps/malware_scan.mako
  concourse/steps/scan_container_images.py
  concourse/templates/default.mako
  dso/model.py
  github/compliance/report.py
  model/clamav.py
  model/concourse.py
  requirements.txt
  setup.py
  test/concourse/model/traits/filter_test.py
Labels: size/xl, needs/review, needs/rebase, needs/ok-to-test, needs/second-opinion

#1006 fix: consider resource-type for referenced resources
  concourse/steps/helmcharts.mako
Labels: needs/review, size/xs, needs/ok-to-test

#1007 Enable people to get notified via slack
  concourse/model/traits/notifications.py
  concourse/steps/notification.mako
  doc/traits/notifications.rst
  doc/traits/slack.rst
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#1008 fix: do not add publish-repository for notification-steps
  concourse/templates/default.mako
Labels: needs/review, size/xs, needs/ok-to-test

#1011 Add option to set timestamp as prerelease in version trait
  concourse/model/traits/version.py
  concourse/steps/component_descriptor.py
  concourse/steps/version.mako
  doc/traits/version.rst
Labels: needs/review, size/xs, needs/ok-to-test

#1009 Add configuration options for compliance milestones
  github/compliance/milestone.py
Labels: needs/review, needs/ok-to-test, size/s

#1010 OCI nits
  oci/client.py
Labels: reviewed/ok-to-test, needs/review, size/xs, needs/ok-to-test

#1013 Also consider "soft" component references in update deps step
  concourse/steps/update_component_deps.py
Labels: needs/review, needs/ok-to-test, size/s

#1018 Allow adding custom annotations to signature manifest
  cosign.py
Labels: needs/review, size/xs, needs/ok-to-test

#1016 Binary data
  cli/gardener_ci/config.py
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#1022 Allow PrefixUploader to join a prefix without added `/`
  ctt/uploaders.py
Labels: needs/review, size/xs, needs/ok-to-test

#1020 cleanup: rm unnecessary checks
  cli/gardener_ci/config.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1023 fix: ignore case for github-url-matching
  model/github.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm

#1025 Don't copy signatures of root component to referenced ones
  ctt/process_dependencies.py
Labels: needs/review, size/xs, needs/ok-to-test

#1026 Only upload cosign signature manifest if it does not exist yet
  cosign.py
Labels: needs/review, size/xs, needs/ok-to-test

#1024 Cleanup build
  .ci/pipeline_definitions
  oci/VERSION
  setup.oci.py
  setup.py
  setup.whd.py
Labels: reviewed/ok-to-test, needs/review, needs/rebase, size/s

#1027 add dev-version-injection compliant w/ python-setuptools
  concourse/model/traits/version.py
  concourse/steps/version.mako
  doc/traits/version.rst
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#1030 fix: also strip trailing `/`
  concourse/steps/release.mako
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm
