Repository gardener/cc-utils, pull requests merged in 2024-12, with the labels that each got.

#1088 Add dedicated `SigningserverException`
  signingserver.py
Labels: needs/review, size/xs

#1092 introduce purpose label for cm06
  dso/labels.py
Labels: size/xs, reviewed/lgtm

#1095 Add backlog and scan-cfg related delivery-service routes
  delivery/client.py
Labels: reviewed/lgtm, size/s

#1094 Purge `DeliveryCfg`
  delivery/jwt.py
  model/delivery.py
  test/delivery/jwt_test.py
Labels: size/m, reviewed/lgtm

#1096 rm dead code
  gitutil.py
  test/gitutil_test.py
Labels: size/m, reviewed/lgtm

#1097 allow configuring release-trait to not publish release-commits
  concourse/model/traits/release.py
  concourse/steps/release.mako
Labels: reviewed/lgtm, size/s

#1100 refactor: let release-notes no longer depend on github-helper
  ccc/github.py
  cli/gardener_ci/_release_notes.py
  concourse/steps/draft_release.mako
  concourse/steps/release.py
  concourse/steps/update_component_deps.py
  release_notes/fetch.py
  release_notes/utils.py
Labels: needs/review, size/s

#1086 Introduce sastfinding as a new finding type
  dso/model.py
Labels: needs/review, size/s

#1102 refactor: pass authtoken-lookup to deliveryservice-client
  ccc/delivery.py
  cli/gardener_ci/_oci.py
  delivery/client.py
Labels: needs/review, size/s, needs/changes

#1103 add build description for gardener-gha-libs
  .github/workflows/build-and-test.yaml
  setup.gha.py
  setup.py
Labels: size/m, reviewed/lgtm

#1104 Lookup job-mapping in multiple sets for WHD PR processing
  whd/pull_request.py
Labels: needs/review, size/xs
