Repository gardener/cc-utils, pull requests merged in 2024-01, with the labels that each got.

#935 Add option to delete old BDBA products
  protecode/client.py
  protecode/scanning.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes

#938 Fix ocm cfg type name
  cnudie/util.py
Labels: needs/review, size/xs, needs/ok-to-test

#939 Add github token rotation for SUGAR
  cfg_mgmt/sugar.py
  model/sugar.py
Labels: reviewed/ok-to-test, needs/review, needs/ok-to-test, size/m

#943 [btp_application_certificate] Store intermediate certificate and send it on client authentication
  cfg_mgmt/btp_application_certificate.py
Labels: reviewed/ok-to-test, size/xs, needs/ok-to-test, reviewed/lgtm
