Repository gardener/cc-utils, pull requests merged in 2024-11, with the labels that each got.

#1070 Consider github-hostname when checking `trusted_teams`
  whd/pull_request.py
Labels: needs/review, needs/ok-to-test, size/s, needs/changes

#1073 fix warning / switch from deprecated attribute
  ccc/elasticsearch.py
Labels: needs/review, size/xs

#1079 also expose ocm-resource-fragments as artefacts
  .github/actions/ocm-oci-build/action.yaml
Labels: size/xs, reviewed/lgtm

#1080 Add mapping from datasource to related datatypes + add `delivery-dashboard` datasource
  dso/model.py
Labels: needs/review, size/s

#1083 Enhance pr body generation to omit component details when length exceeds
  concourse/steps/update_component_deps.py
  test/cnudie/cnudie_util_test.py
Labels: reviewed/lgtm, size/s

#1084 Enhance signingserver client
  signingserver.py
  test/signingserver_test.py
Labels: needs/review, size/s

#1085 Consider change of digests in tgt ref for image filtering
  container/util.py
  ctt/process_dependencies.py
Labels: needs/review, size/xs
