Repository gardener/cc-utils, pull requests merged in 2025-01, with the labels that each got.

#1112 cleanup: do not unncecessarily configure logger
  ccc/delivery.py
  model/__init__.py
Labels: size/xs, reviewed/lgtm

#1113 gardener-gha-libs installer action
  .github/actions/install-gardener-gha-libs/action.yaml
Labels: size/xs, reviewed/lgtm

#1116 Add hint to missing pipeline step error
  concourse/model/traits/release.py
Labels: needs/review, size/xs

#1119 Remove dead code
  github/compliance/model.py
  github/compliance/report.py
Labels: needs/review, size/s

#1120 Add flag to disable asset upload as github release asset
  concourse/model/traits/release.py
  concourse/steps/release.mako
Labels: needs/review, size/xs

#1130 Drop (now) unused input parameter `release-to-pypi`
  .github/workflows/build-and-test.yaml
  .github/workflows/release.yaml
Labels: needs/review, size/xs

#1128 Heldkat patch 1
  cli/gardener_ci/compliance.py
Labels: needs/review, size/xs, needs/changes

#1127 migrate cc pipeline to gha
  .github/actions/setup-git-identity/action.yaml
  .github/workflows/cc-job-image-base.yaml
  Dockerfile.job-image-base
  JOB_IMAGE_BASE_VERSION
  apk-packages.blacklist
Labels: needs/review, size/m, needs/changes

#1134 fix: rename draft-releases upon promotion to final release
  concourse/steps/release.mako
Labels: size/xs, reviewed/lgtm

#1138 fix another regression: set draft-name
  concourse/steps/draft_release.mako
Labels: size/xs, reviewed/lgtm

#1139 Unpin dacite version (again)
  .github/workflows/build-and-test.yaml
  requirements.oci.txt
  requirements.ocm.txt
  requirements.txt
Labels: needs/review, size/xs

#1135 extract update-dockerfile step to its own workflow
  .github/workflows/cc-job-image-base.yaml
  .github/workflows/update-dockerfile.yaml
Labels: needs/review, size/m
