Repository gardener/cc-utils, pull requests merged in 2025-04, with the labels that each got.

#1166 dso: add models for findings from gardener/inventory
  dso/model.py
Labels: needs/review, needs/rebase, size/s

#1201 always declare `version` as extraIdentity for pipeline-built images
  .github/workflows/oci-ocm.yaml
  concourse/steps/component_descriptor.mako
Labels: needs/review, size/xs

#1208 fix dependency order by installing bdba pkg before gardener-cicd-cfg-mgt
  .github/workflows/build-and-test.yaml
Labels: size/xs, reviewed/lgtm

#1203 Update OCM-spec according to upstream schema
  ocm/__init__.py
  ocm/ocm-component-descriptor-schema.yaml
Labels: reviewed/lgtm, size/s

#1210 Drop OCM cli from job-image
  Dockerfile
Labels: needs/review, size/xs

#1211 use consistent osid variant across codebase
  dso/model.py
Labels: size/xs, reviewed/lgtm

#1212 drop obsolete / unused dependencies
  requirements.txt
  setup.gha.py
Labels: size/xs, reviewed/lgtm

#1214 Use `alpine:edge` for alpine-sap-image
  Dockerfile.alpine-sap
Labels: size/xs, reviewed/lgtm

#1213 Add `verify` flag to OCM component descriptor normalisation
  ocm/sign.py
Labels: needs/review, size/s

#1216 add status description to osidfinding dataclass
  dso/model.py
Labels: needs/review, size/xs

#1202 Add post_release_callback to release trait
  concourse/steps/release.mako
  concourse/steps/release.py
Labels: size/xs, reviewed/lgtm

#1226 add resuable workflow for building helmcharts w/ OCM
  .github/workflows/helmchart-ocm.yaml
Labels: size/m, reviewed/lgtm
