Repository gardener/cc-utils, pull requests merged in 2025-09, with the labels that each got.

#1348 Pass-through OCI registry inputs to `prepare.yaml` workflow
  .github/workflows/upgrade-dependencies.yaml
Labels: needs/review, size/xs

#1350 Always try OCI-Auth prior to OCI image build
  .github/workflows/oci-ocm.yaml
Labels: needs/review, size/xs

#1351 Use recommended Bot accounts for GHA based on GH instance
  .github/actions/setup-git-identity/action.yaml
Labels: needs/review, size/s

#1356 pass whither-component-descriptor to set-dependency-version callback
  .github/actions/ocm-upgrade/ocm_upgrade.py
  github/pullrequest.py
Labels: needs/review, size/xs

#1359 Allow overwriting of resource version in imagevector via resource-id
  ocm/gardener.py
Labels: needs/review, size/xs

#1372 Introduce upstream gating
  .github/actions/ocm-upgrade/action.yaml
  .github/actions/ocm-upgrade/ocm_upgrade.py
Labels: size/m, reviewed/lgtm

#1377 Omit "null" properties from OCI manifest during replication
  ctt/replicate.py
Labels: needs/review, size/xs

#1384 merge last two jobs to improve performance
  .github/workflows/prepare.yaml
Labels: needs/review, size/s

#1367 Add image update for provider extensions
  .github/actions/update-extension-provider-images/action.yaml
  .github/actions/update-extension-provider-images/update-images.py
  .github/workflows/update-extension-provider-images.yaml
Labels: size/xl, needs/review, needs/second-opinion, needs/changes
