Repository gardener/cc-utils, pull requests merged in 2025-03, with the labels that each got.

#1178 also attach release-notes for release-GHA
  .github/actions/release/action.yaml
Labels: needs/review, size/s

#1180 Add ruleset and rule names to DikiFinding
  dso/model.py
Labels: size/xs, reviewed/lgtm

#1181 Export ocm fragments action
  .github/actions/export-ocm-fragments/action.yaml
  .github/actions/export-ocm-fragments/export_ocm.py
Labels: size/m, reviewed/lgtm

#1183 add merge-ocm-fragments-action
  .github/actions/merge-ocm-fragments/action.yaml
Labels: size/m, reviewed/lgtm

#1177 Drop `correlation_id` from snapshots and add utility function
  dso/model.py
Labels: needs/review, size/xs

#1165 Add model classes for ODG crypto extension
  dso/model.py
  github/compliance/issue.py
Labels: needs/review, size/m

#1184 Move `artifact_url` function to `ocm.util` module
  github/compliance/report.py
  ocm/util.py
Labels: needs/review, size/s

#1175 Falco event modeling
  dso/model.py
Labels: size/m, reviewed/lgtm

#1193 purge checkmarx-scan-trait, and related code
  checkmarx/__init__.py
  checkmarx/client.py
  checkmarx/model.py
  checkmarx/project.py
  checkmarx/tablefmt.py
  checkmarx/util.py
  concourse/model/traits/__init__.py
  concourse/model/traits/scan_sources.py
  concourse/steps/scan_sources.mako
  concourse/steps/scan_sources.py
  concourse/templates/default.mako
  doc/traits.rst
  doc/traits/scan_sources.rst
  dso/labels.py
  dso/model.py
  github/compliance/issue.py
  github/compliance/report.py
  model/checkmarx.py
  setup.gha.py
Labels: size/xl, reviewed/lgtm

#1194 Improve export ocm fragments action
  .github/actions/export-ocm-fragments/action.yaml
Labels: size/xs, reviewed/lgtm
