Repository gardener/cc-utils, pull requests merged in 2025-06, with the labels that each got.

#1258 Prepare delivery-service short-lived session tokens
  delivery/client.py
  delivery/jwt.py
Labels: size/xs, reviewed/lgtm

#1259 Always call update-dependency callback (if script exists)
  .github/actions/ocm-upgrade/ocm_upgrade.py
Labels: needs/review, size/s

#1262 Push only if possible
  .github/actions/helmchart/action.yaml
  .github/actions/helmchart/helm.py
  .github/workflows/helmchart-ocm.yaml
  .github/workflows/oci-ocm.yaml
Labels: size/m, reviewed/lgtm

#1270 Prepare action hook
  .github/actions/ocm-upgrade/action.yaml
  .github/workflows/upgrade-dependencies.yaml
Labels: reviewed/lgtm, size/s

#1271 allow (re-)setting of extra-tags for OCI-OCM-Workflow
  .github/workflows/oci-ocm.yaml
  oci/merge.py
Labels: needs/review, size/xs
