Repository gardener/cc-utils, pull requests merged in 2025-07, with the labels that each got.

#1275 add opinionated sast-lint-workflow
  .github/workflows/sastlint-ocm.yaml
Labels: needs/review, size/s

#1276 Allow specification of `merge-[policy|method]` in upgrade workflow
  .github/workflows/upgrade-dependencies.yaml
Labels: needs/review, size/xs

#1278 Resolve references of `ccc` module in CTT
  ctt/process_dependencies.py
  ctt/replicate.py
Labels: needs/review, size/s

#1282 add convenience-function for creating oci-client w/ docker-auth
  oci/client.py
Labels: size/xs, reviewed/lgtm

#1284 Consistently use Git config from `setup-git-identity` GitHub Action
  .github/actions/ocm-upgrade/ocm_upgrade.py
  .github/actions/release-notes/action.yaml
  .github/actions/release-notes/release_notes_cli.py
Labels: needs/review, size/xs

#1285 add GitHub-Action for oidc-auth against k8s-apiservers
  .github/actions/kubernetes-auth/action.yaml
Labels: needs/review, size/m

#1283 refactor: relocate helmchart-imagemap processing
  ocm/helm.py
  ocm/util.py
Labels: size/m, reviewed/lgtm

#1297 Fix max_level logic for linting
  ci/util.py
Labels: needs/review, size/xs

#1298 allow specification of additional release-assets
  .github/actions/release/action.yaml
  .github/actions/release/release.py
  .github/workflows/release.yaml
Labels: needs/review, size/m

#1301 fix: Don't evaluate backticks "`" in draft release notes
  .github/actions/draft-release/action.yaml
Labels: needs/review, size/xs

#1302 make writing of release-notes more robust
  .github/actions/draft-release/action.yaml
Labels: size/xs, reviewed/lgtm

#1305 Fix special handling for modified root component descriptor in CTT
  ctt/process_dependencies.py
Labels: size/xs, reviewed/lgtm

#1307 Fix: Include BoM-Diff in UPR if there is space left (not vice-versa)
  github/pullrequest.py
Labels: needs/review, size/xs

#1295 write testrunner-output to summary
  .github/workflows/run-testmachinery-tests.yaml
Labels: reviewed/lgtm, size/s

#1313 split oci-image-building and -pushing into two steps
  .github/workflows/oci-ocm.yaml
Labels: size/xs, reviewed/lgtm

#1314 fail if localBlob's file is not present
  .github/actions/export-ocm-fragments/action.yaml
Labels: size/xs, reviewed/lgtm

#1312 Add support to create Helm chart image mappings containing references to resources of sub-components
  .github/actions/helmchart/action.yaml
  .github/actions/helmchart/helm.py
  .github/actions/helmchart/helm_test.py
  .github/workflows/helmchart-ocm.yaml
  concourse/model/traits/publish.py
  ocm/helm.py
Labels: needs/review, size/m

#1316 Fix detection of obsolete pullrequests
  github/pullrequest.py
Labels: size/xs, reviewed/lgtm

#1322 let trusted-checkout honour "ok-to-test"-label
  .github/actions/trusted-checkout/action.yaml
Labels: needs/review, size/s

#1324 additionally upload component-descriptor as artifact
  .github/actions/release/action.yaml
  .github/workflows/post-build.yaml
Labels: needs/review, size/xs
