Repository gardener/cc-utils, pull requests merged in 2025-02, with the labels that each got.

#1136 Drop `cfg_name` property from compliance snapshots
  dso/model.py
Labels: needs/review, size/xs

#1143 Rm some hyperscaler client factories
  ccc/alicloud.py
  ccc/aws.py
  ccc/gcp.py
Labels: needs/review, size/m

#1151 Gha fork handling
  .github/workflows/build-and-test.yaml
Labels: size/xs, reviewed/lgtm

#1152 use version-action in build-and-test-workflow
  .github/workflows/build-and-test.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
Labels: reviewed/lgtm, size/s

#1157 fix: prevent duplicate pr creation
  .github/workflows/update-dockerfile.yaml
Labels: needs/review, size/s

#1159 introduce rescoringclass for SAST
  dso/model.py
Labels: size/xs, reviewed/lgtm

#1163 Bump commit prerelease
  .github/actions/release/action.yaml
  .github/actions/version/action.yaml
  .github/actions/version/version_cli.py
  .github/workflows/build-and-test.yaml
  .github/workflows/non-release.yaml
  .github/workflows/release.yaml
Labels: reviewed/lgtm, size/s

#1160 introduce action to check if repo is a fork
  .github/actions/repo-metadata/action.yaml
  .github/workflows/build-and-test.yaml
  .github/workflows/update-dockerfile.yaml
Labels: needs/review, size/s, needs/changes

#1167 support SAST issue tracking
  github/compliance/issue.py
Labels: needs/review, size/xs

#1170 fix: expose release-notes as output m(((
  .github/actions/release-notes/action.yaml
Labels: needs/review, size/xs

#1176 add release-notes as inline-resource to component-descriptors
  concourse/steps/release.mako
Labels: reviewed/lgtm, size/s

#1179 Prevent naming conflicts by renaming sast value
  dso/model.py
Labels: size/xs, reviewed/lgtm
