Repository gardener/cc-utils, pull requests merged in 2025-05, with the labels that each got.

#1229 Don't raise upon 404 on DELETE manifest operations per default
  cnudie/purge.py
  oci/client.py
  oci/client_async.py
Labels: reviewed/lgtm, size/s

#1230 Allow oci-client without credential-lookup (anonymous auth)
  oci/client.py
Labels: size/xs, reviewed/lgtm

#1231 Drop dependency towards bdba client
  .github/workflows/build-and-test.yaml
  .ocm/base-component.yaml
Labels: size/xs, reviewed/lgtm

#1232 default to org-secret
  .github/workflows/release.yaml
Labels: size/xs, reviewed/lgtm

#1235 fix: Pass cfg-factory if provided
  ccc/delivery.py
Labels: reviewed/lgtm, size/s

#1234 Fix: Upload release notes as asset in case it was truncated
  concourse/steps/release.mako
Labels: size/xs, reviewed/lgtm

#1239 fix: do not overwrite (patched) OCI manifest
  oci/__init__.py
Labels: needs/review, size/xs

#1240 Only publish documentation on head updates of default branch
  .github/workflows/build-and-test.yaml
Labels: needs/review, size/xs

#1242 add `component-descriptor` workflow
  .github/workflows/component-descriptor.yaml
  .github/workflows/non-release.yaml
Labels: needs/review, size/s

#1248 limit size of commit-objects output from capture-commit action
  .github/actions/capture-commit/action.yaml
  .github/workflows/build-and-test.yaml
  .github/workflows/prepare.yaml
Labels: size/xs, reviewed/lgtm
