Repository gardener/cc-utils, pull requests merged in 2025-10, with the labels that each got.

#1392 fix(ci): Use trusted-checkout also for job-image-base
  .github/workflows/cc-job-image-base.yaml
Labels: needs/review, size/xs

#1393 Fix multi-line output handling in workflow and action
  .github/actions/update-extension-provider-images/action.yaml
  .github/workflows/update-extension-provider-images.yaml
Labels: needs/review, size/xs, reviewed/lgtm

#1396 Fix double minor version additions in update images GHA
  .github/actions/update-extension-provider-images/update-images.py
  .github/workflows/update-extension-provider-images.yaml
Labels: reviewed/lgtm, size/s
