Repository gardener/cc-utils, pull requests merged in 2025-08, with the labels that each got.

#1332 fix: Create upgrade-PR if whence-version differs
  concourse/steps/update_component_deps.mako
  concourse/steps/update_component_deps.py
  github/pullrequest.py
Labels: needs/review, size/m

#1333 expose published component-descriptor as output
  .github/actions/release/action.yaml
  .github/workflows/release.yaml
Labels: size/xs, reviewed/lgtm

#1335 Fixate commit for pullrequests
  .github/actions/trusted-checkout/action.yaml
Labels: reviewed/lgtm, size/s

#1339 make inclusion of subcomponents' release-notes configurable
  .github/actions/release-notes/action.yaml
  .github/actions/release-notes/release_notes_cli.py
  .github/workflows/draft-release.yaml
  .github/workflows/post-build.yaml
  .github/workflows/release.yaml
Labels: size/m, reviewed/lgtm

#1319 Add machine-readable release notes archive
  .github/actions/ocm-upgrade/ocm_upgrade.py
  .github/actions/release-notes/action.yaml
  .github/actions/release-notes/release_notes_cli.py
  .github/actions/release/action.yaml
  cli/gardener_ci/_release_notes.py
  concourse/steps/draft_release.mako
  concourse/steps/release.mako
  concourse/steps/release.py
  concourse/steps/update_component_deps.py
  gitutil.py
  release_notes/fetch.py
  release_notes/markdown.py
  release_notes/model.py
  release_notes/ocm.py
  release_notes/utils.py
Labels: size/xl, needs/review, needs/second-opinion, needs/changes

#1345 Allow cfg of full vs. local release-notes for Slack posting on Concourse
  concourse/model/traits/slack.py
  concourse/steps/release.mako
  doc/release_notes.rst
Labels: needs/review, size/xs

#1344 pass "commit-kind" to called version-callback-actions
  .github/actions/release/action.yaml
  .github/actions/version/action.yaml
  .github/workflows/prepare.yaml
Labels: needs/review, size/xs

#1346 Adapt linter to fail if warning or higher levels are found
  ci/util.py
Labels: needs/review, size/xs, needs/changes

#1347 feat(gha): Add resource release-notes again
  .github/actions/release-notes/release_notes_cli.py
Labels: needs/review, size/xs, needs/changes
